name: social_connect
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase (Updated to compatible versions to fix build errors)
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.5

  # Image (Updated to latest versions)
  image_picker: ^1.1.2
  cloudinary_public: ^0.23.1
  video_player: ^2.8.6

  # UI & Utility
  google_fonts: ^6.2.1
  intl: ^0.19.0
  provider: ^6.1.2

  # ... other packages
  firebase_messaging: ^14.9.0
  uuid: ^4.4.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Moved this here, as it's a development-only tool
  change_app_package_name: ^1.5.0

  flutter_lints: ^2.0.0
  
  # Added for app icon
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

# Added for app icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21